In [1]:
# ECON662D1 Assignment 2 - Jean-Sébastien Matte

In [2]:
# import modules
import numpy as np
import pandas as pd
import scipy as sp
import statsmodels.api as sm

In [3]:
# load data
in_dir = '...'
in_file = str(in_dir + '/ass2_dat.txt')
df = pd.read_csv(in_file, sep = '\s+', header = None)
print(df)

              0          1          2          3
0    332.597273   91.52508  -7.879150  -22.82027
1     42.119419   58.32108 -10.377350  -46.89894
2    310.603232   71.19264   8.240685  -83.72890
3   1087.981690   85.37536  -7.939428  -98.93214
4    291.950898   84.63815  28.309510  -80.68243
..          ...        ...        ...        ...
95  1696.762100   26.54987 -40.947840 -146.96500
96   728.001441   69.94029  75.729620 -126.41690
97   539.483943   89.50351 -44.335000  -76.11952
98    21.440609  100.67600  48.674720  -16.33207
99   305.192266  133.57730   4.789128  -10.57532

[100 rows x 4 columns]


In [4]:
df.columns = ['y', 'x1', 'x2', 'x3']
print(df)

              y         x1         x2         x3
0    332.597273   91.52508  -7.879150  -22.82027
1     42.119419   58.32108 -10.377350  -46.89894
2    310.603232   71.19264   8.240685  -83.72890
3   1087.981690   85.37536  -7.939428  -98.93214
4    291.950898   84.63815  28.309510  -80.68243
..          ...        ...        ...        ...
95  1696.762100   26.54987 -40.947840 -146.96500
96   728.001441   69.94029  75.729620 -126.41690
97   539.483943   89.50351 -44.335000  -76.11952
98    21.440609  100.67600  48.674720  -16.33207
99   305.192266  133.57730   4.789128  -10.57532

[100 rows x 4 columns]


In [5]:
# create matrix X of the regressors
X = np.zeros((len(df),4))
for i in range(X.shape[0]):
    X[i] = [1, df.x1.values[i], df.x2.values[i], df.x3.values[i]]
print(X.shape)

# create vector y of observations
y = np.array([[j] for j in df.y.values])
print(y.shape)

# regression model
model = sm.OLS(y, X).fit()
print(model.summary())
print()
print('Residual Std. Error: ',  np.sqrt(model.scale))

(100, 4)
(100, 1)
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.626
Model:                            OLS   Adj. R-squared:                  0.614
Method:                 Least Squares   F-statistic:                     53.54
Date:                Sun, 15 Nov 2020   Prob (F-statistic):           2.00e-20
Time:                        18:31:50   Log-Likelihood:                -679.21
No. Observations:                 100   AIC:                             1366.
Df Residuals:                      96   BIC:                             1377.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -307.9884    117.223  

In [6]:
# Model parameters
print(model.params)
beta0 = model.params[0]
beta1 = model.params[1]
beta2 = model.params[2]
beta3 = model.params[3]

[-307.98841316    3.91597727   -4.02059773   -8.48159487]


In [7]:
# predictions, residuals and disturbances
pred = model.fittedvalues
print(pred.shape)

resid = model.resid
print(resid.shape)

dist = []
for m in range(len(y)):
    dist.append(y[m][0] - beta0 - beta1*X[m][1] - beta2*X[m][2] - beta3*X[m][3])
print(len(dist))

(100,)
(100,)
100


In [8]:
# Regression models for the HCCME estimates
model_HC0 = sm.OLS(y, X).fit(cov_type = 'HC0')
print(model_HC0.summary())
print('Residual Std. Error: ',  np.sqrt(model_HC0.scale))
print('')

model_HC1 = sm.OLS(y, X).fit(cov_type = 'HC1')
print(model_HC1.summary())
print('Residual Std. Error: ',  np.sqrt(model_HC1.scale))
print('')

model_HC2 = sm.OLS(y, X).fit(cov_type = 'HC2')
print(model_HC2.summary())
print('Residual Std. Error: ',  np.sqrt(model_HC2.scale))
print('')

model_HC3 = sm.OLS(y, X).fit(cov_type = 'HC3')
print(model_HC3.summary())
print('Residual Std. Error: ',  np.sqrt(model_HC3.scale))
print('')

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.626
Model:                            OLS   Adj. R-squared:                  0.614
Method:                 Least Squares   F-statistic:                     28.47
Date:                Sun, 15 Nov 2020   Prob (F-statistic):           2.96e-13
Time:                        18:31:50   Log-Likelihood:                -679.21
No. Observations:                 100   AIC:                             1366.
Df Residuals:                      96   BIC:                             1377.
Df Model:                           3                                         
Covariance Type:                  HC0                                         
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const       -307.9884    111.593     -2.760      0.0

In [9]:
# Regression models for the estimators using Newey-West HAC
model1_p2 = sm.OLS(y, X).fit(cov_type = 'HAC', cov_kwds={'maxlags':2})
print(model1_p2.summary())
print('Residual Std. Error: ',  np.sqrt(model1_p2.scale))
print('')

model1_p3 = sm.OLS(y, X).fit(cov_type = 'HAC', cov_kwds={'maxlags':3})
print(model1_p3.summary())
print('Residual Std. Error: ',  np.sqrt(model1_p3.scale))
print('')

model1_p4 = sm.OLS(y, X).fit(cov_type = 'HAC', cov_kwds={'maxlags':4})
print(model1_p4.summary())
print('Residual Std. Error: ',  np.sqrt(model1_p4.scale))
print('')

model1_p5 = sm.OLS(y, X).fit(cov_type = 'HAC', cov_kwds={'maxlags':5})
print(model1_p5.summary())
print('Residual Std. Error: ',  np.sqrt(model1_p5.scale))
print('')

model1_p6 = sm.OLS(y, X).fit(cov_type = 'HAC', cov_kwds={'maxlags':6})
print(model1_p6.summary())
print('Residual Std. Error: ',  np.sqrt(model1_p6.scale))
print('')

model1_p20 = sm.OLS(y, X).fit(cov_type = 'HAC', cov_kwds={'maxlags':20})
print(model1_p20.summary())
print('Residual Std. Error: ',  np.sqrt(model1_p20.scale))
print('')

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.626
Model:                            OLS   Adj. R-squared:                  0.614
Method:                 Least Squares   F-statistic:                     31.91
Date:                Sun, 15 Nov 2020   Prob (F-statistic):           2.14e-14
Time:                        18:31:51   Log-Likelihood:                -679.21
No. Observations:                 100   AIC:                             1366.
Df Residuals:                      96   BIC:                             1377.
Df Model:                           3                                         
Covariance Type:                  HAC                                         
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const       -307.9884    126.297     -2.439      0.0

In [10]:
# a) estimates of the covariance matrix of \hat{\beta}
# i) standard OLS estimate
# ii) HCo, HC1, HC2, HC3, HC4
# iii) Newwy-West HAC

In [11]:
# i) standard OLS estimate
sum_resid_squared = 0
for r in resid:
    sum_resid_squared += r**2
Vhat_i = (1 / (len(y) - 4)) * sum_resid_squared * np.linalg.inv(np.matmul(X.T, X))
print(Vhat_i)
print('')
print(model.cov_params())

[[ 1.37412989e+04 -1.14577856e+02  8.04444087e+00  6.76760297e+01]
 [-1.14577856e+02  1.10947664e+00 -1.64873513e-01 -4.22071133e-01]
 [ 8.04444087e+00 -1.64873513e-01  8.34828446e-01 -1.68916430e-02]
 [ 6.76760297e+01 -4.22071133e-01 -1.68916430e-02  5.74773180e-01]]

[[ 1.37412989e+04 -1.14577856e+02  8.04444087e+00  6.76760297e+01]
 [-1.14577856e+02  1.10947664e+00 -1.64873513e-01 -4.22071133e-01]
 [ 8.04444087e+00 -1.64873513e-01  8.34828446e-01 -1.68916430e-02]
 [ 6.76760297e+01 -4.22071133e-01 -1.68916430e-02  5.74773180e-01]]


In [12]:
# ii) HC0, HC1, HC2, HC3, HC4
print('HC0')
Ohat_HC0 = np.zeros((len(y),len(y)))
for i0 in range(len(y)):
    Ohat_HC0[i0][i0] = resid[i0]**2
    
Vhat_ii_HC0 = np.matmul(np.matmul(np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T, X)), X.T), Ohat_HC0), X), np.linalg.inv(np.matmul(X.T, X)))
print(Vhat_ii_HC0)
print('')
print(model.cov_HC0)
print('')

print('HC1')
Ohat_HC1 = np.zeros((len(y),len(y)))
for i1 in range(len(y)):
    Ohat_HC1[i1][i1] = dist[i1]**2
    
Vhat_ii_HC1 = (len(y) / (len(y) - 4)) * np.matmul(np.matmul(np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T, X)), X.T), Ohat_HC1), X), np.linalg.inv(np.matmul(X.T, X)))
print(Vhat_ii_HC1)
print('')
print(model.cov_HC1)
print('')

print('HC2')
Px = np.matmul(X, np.matmul(np.linalg.inv(np.matmul(X.T, X)), X.T))

Ohat_HC2 = np.zeros((len(y),len(y)))
for i2 in range(len(y)):
    Ohat_HC2[i2][i2] = resid[i2]**2 / (1 - Px[i2][i2])
    
Vhat_ii_HC2 = np.matmul(np.matmul(np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T, X)), X.T), Ohat_HC2), X), np.linalg.inv(np.matmul(X.T, X)))
print(Vhat_ii_HC2)
print('')
print(model.cov_HC2)
print('')

print('HC3')
Ohat_HC3 = np.zeros((len(y),len(y)))
for i3 in range(len(y)):
    Ohat_HC3[i3][i3] = resid[i3]**2 / ((1 - Px[i3][i3])**2)
    
Vhat_ii_HC3 = np.matmul(np.matmul(np.matmul(np.matmul(np.linalg.inv(np.matmul(X.T, X)), X.T), Ohat_HC3), X), np.linalg.inv(np.matmul(X.T, X)))
print(Vhat_ii_HC3)
print('')
print(model.cov_HC3)
print('')

HC0
[[ 1.24530797e+04 -9.57197205e+01 -3.72882783e+00  8.31958443e+01]
 [-9.57197205e+01  8.66960180e-01  6.63431413e-02 -4.32988909e-01]
 [-3.72882783e+00  6.63431413e-02  5.68223212e-01  1.48052795e-01]
 [ 8.31958443e+01 -4.32988909e-01  1.48052795e-01  1.03751374e+00]]

[[ 1.24530797e+04 -9.57197205e+01 -3.72882783e+00  8.31958443e+01]
 [-9.57197205e+01  8.66960180e-01  6.63431413e-02 -4.32988909e-01]
 [-3.72882783e+00  6.63431413e-02  5.68223212e-01  1.48052795e-01]
 [ 8.31958443e+01 -4.32988909e-01  1.48052795e-01  1.03751374e+00]]

HC1
[[ 1.29719580e+04 -9.97080422e+01 -3.88419566e+00  8.66623378e+01]
 [-9.97080422e+01  9.03083521e-01  6.91074389e-02 -4.51030114e-01]
 [-3.88419566e+00  6.91074389e-02  5.91899179e-01  1.54221662e-01]
 [ 8.66623378e+01 -4.51030114e-01  1.54221662e-01  1.08074348e+00]]

[[ 1.29719580e+04 -9.97080422e+01 -3.88419566e+00  8.66623378e+01]
 [-9.97080422e+01  9.03083521e-01  6.91074389e-02 -4.51030114e-01]
 [-3.88419566e+00  6.91074389e-02  5.91899179e-0

In [13]:
# iii) Newwy-West HAC
print('Newwy-West HAC w/ p = 2')
print(model1_p2.cov_params())
print('')

print('Newwy-West HAC w/ p = 3')
print(model1_p3.cov_params())
print('')

print('Newwy-West HAC w/ p = 4')
print(model1_p4.cov_params())
print('')

print('Newwy-West HAC w/ p = 5')
print(model1_p5.cov_params())
print('')

print('Newwy-West HAC w/ p = 6')
print(model1_p6.cov_params())
print('')

print('Newwy-West HAC w/ p = 20')
print(model1_p20.cov_params())
print('')

Newwy-West HAC w/ p = 2
[[ 1.59509096e+04 -1.22007262e+02 -2.11055587e+01  1.03853863e+02]
 [-1.22007262e+02  1.08197167e+00  2.07669560e-01 -5.89471279e-01]
 [-2.11055587e+01  2.07669560e-01  4.82978011e-01  2.08198238e-02]
 [ 1.03853863e+02 -5.89471279e-01  2.08198238e-02  1.15960685e+00]]

Newwy-West HAC w/ p = 3
[[ 1.75247862e+04 -1.34764371e+02 -2.15287723e+01  1.13868420e+02]
 [-1.34764371e+02  1.19271959e+00  2.04323007e-01 -6.73921285e-01]
 [-2.15287723e+01  2.04323007e-01  4.30557868e-01 -1.02780512e-02]
 [ 1.13868420e+02 -6.73921285e-01 -1.02780512e-02  1.20728311e+00]]

Newwy-West HAC w/ p = 4
[[ 1.88068237e+04 -1.45722111e+02 -2.41397044e+01  1.21547593e+02]
 [-1.45722111e+02  1.28691700e+00  2.29229787e-01 -7.48750302e-01]
 [-2.41397044e+01  2.29229787e-01  4.07763454e-01 -2.93807103e-02]
 [ 1.21547593e+02 -7.48750302e-01 -2.93807103e-02  1.23628549e+00]]

Newwy-West HAC w/ p = 5
[[ 1.94330580e+04 -1.52904486e+02 -2.60800872e+01  1.22972767e+02]
 [-1.52904486e+02  1.356429

In [14]:
# 2 standard error of the estimate of coefficient x3 (i.e. standard error of \hat{\beta_{3}})

In [15]:
# i) standard OLS estimate
sehat_i = []
for ii00 in range(Vhat_i.shape[0]):
    sehat_i.append(np.sqrt(Vhat_i[ii00][ii00]))
print(sehat_i)
print(model.bse)

[117.22328657123343, 1.0533169689314066, 0.9136894693599791, 0.7581379691371817]
[117.22328657   1.05331697   0.91368947   0.75813797]


In [16]:
# ii) HC0, HC1, HC2, HC3, HC4
print('HC0')
sehat_ii_HC0 = []
for ii0 in range(Vhat_ii_HC0.shape[0]):
    sehat_ii_HC0.append(np.sqrt(Vhat_ii_HC0[ii0][ii0]))
print(sehat_ii_HC0)
print(model.HC0_se)
print('')

print('HC1')
sehat_ii_HC1 = []
for ii1 in range(Vhat_ii_HC1.shape[0]):
    sehat_ii_HC1.append(np.sqrt(Vhat_ii_HC1[ii1][ii1]))
print(sehat_ii_HC1)
print(model.HC1_se)
print('')

print('HC2')
sehat_ii_HC2 = []
for ii2 in range(Vhat_ii_HC2.shape[0]):
    sehat_ii_HC2.append(np.sqrt(Vhat_ii_HC2[ii2][ii2]))
print(sehat_ii_HC2)
print(model.HC2_se)
print('')

print('HC3')
sehat_ii_HC3 = []
for ii3 in range(Vhat_ii_HC3.shape[0]):
    sehat_ii_HC3.append(np.sqrt(Vhat_ii_HC3[ii3][ii3]))
print(sehat_ii_HC3)
print(model.HC3_se)
print('')

HC0
[111.59336747123938, 0.9311069647790416, 0.7538058185703573, 1.0185841832968705]
[111.59336747   0.93110696   0.75380582   1.01858418]

HC1
[113.89450374309783, 0.9503070665251001, 0.7693498419326531, 1.039588128811194]
[113.89450374   0.95030707   0.76934984   1.03958813]

HC2
[114.67872372489616, 0.9546078801628803, 0.7784814257874627, 1.0580544663538576]
[114.67872372   0.95460788   0.77848143   1.05805447]

HC3
[117.88573394244081, 0.9789952919316698, 0.8043183230632619, 1.0993814641866588]
[117.88573394   0.97899529   0.80431832   1.09938146]



In [17]:
# iii) Newwy-West HAC
print('Newwy-West HAC w/ p = 2')
print(model1_p2.bse)
print('')

print('Newwy-West HAC w/ p = 3')
print(model1_p3.bse)
print('')

print('Newwy-West HAC w/ p = 4')
print(model1_p4.bse)
print('')

print('Newwy-West HAC w/ p = 5')
print(model1_p5.bse)
print('')

print('Newwy-West HAC w/ p = 6')
print(model1_p6.bse)
print('')

print('Newwy-West HAC w/ p = 20')
print(model1_p20.bse)
print('')

Newwy-West HAC w/ p = 2
[126.29691055   1.04017867   0.69496619   1.07685043]

Newwy-West HAC w/ p = 3
[132.38121555   1.09211702   0.65616908   1.09876436]

Newwy-West HAC w/ p = 4
[137.13797317   1.13442364   0.63856359   1.11188376]

Newwy-West HAC w/ p = 5
[139.40250368   1.16465864   0.62493482   1.09951993]

Newwy-West HAC w/ p = 6
[139.95256014   1.18460753   0.62411637   1.08510123]

Newwy-West HAC w/ p = 20
[156.48195605   1.3745425    0.54249479   1.18731194]

